"""add repository commit hash

Revision ID: eb2e266c5536
Revises: 4a165c91f306
Create Date: 2026-08-12 16:01:48.493632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb2e266c5536'
down_revision: Union[str, Sequence[str], None] = '4a165c91f306'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('commit_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'commit_hash')
    # ### end Alembic commands ###
