"""add code chunks

Revision ID: ffdd784306af
Revises: eb2e266c5536
Create Date: 2026-08-17 18:12:41.558237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdd784306af'
down_revision: Union[str, Sequence[str], None] = 'eb2e266c5536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=True),
    sa.Column('symbol_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_chunks_file_id'), 'code_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_code_chunks_id'), 'code_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_code_chunks_symbol_id'), 'code_chunks', ['symbol_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_chunks_symbol_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_id'), table_name='code_chunks')
    op.drop_index(op.f('ix_code_chunks_file_id'), table_name='code_chunks')
    op.drop_table('code_chunks')
    # ### end Alembic commands ###
